// Array of Lithuanian letters with corresponding audio file paths
const letters = [
    { char: 'A', audio: 'audio/A.m4a' },
    { char: 'Ą', audio: 'audio/A1.m4a' },
    { char: 'B', audio: 'audio/B.m4a' },
    { char: 'C', audio: 'audio/C.m4a' },
    { char: 'Č', audio: 'audio/C1.m4a' },
    { char: 'D', audio: 'audio/D.m4a' },
    { char: 'E', audio: 'audio/E.m4a' },
    { char: 'Ę', audio: 'audio/E1.m4a' },
    { char: 'Ė', audio: 'audio/E2.m4a' },
    { char: 'F', audio: 'audio/F.m4a' },
    { char: 'G', audio: 'audio/G.m4a' },
    { char: 'H', audio: 'audio/H.m4a' },
    { char: 'I', audio: 'audio/I.m4a' },
    { char: 'Y', audio: 'audio/Y.m4a' },
    { char: 'J', audio: 'audio/J.m4a' },
    { char: 'K', audio: 'audio/K.m4a' },
    { char: 'L', audio: 'audio/L.m4a' },
    { char: 'M', audio: 'audio/M.m4a' },
    { char: 'N', audio: 'audio/N.m4a' },
    { char: 'O', audio: 'audio/O.m4a' },
    { char: 'P', audio: 'audio/P.m4a' },
    { char: 'R', audio: 'audio/R.m4a' },
    { char: 'S', audio: 'audio/S.m4a' },
    { char: 'Š', audio: 'audio/S1.m4a' },
    { char: 'T', audio: 'audio/T.m4a' },
    { char: 'U', audio: 'audio/U.m4a' },
    { char: 'Ų', audio: 'audio/U2.m4a' },
    { char: 'Ū', audio: 'audio/U1.m4a' },
    { char: 'V', audio: 'audio/V.m4a' },
    { char: 'Z', audio: 'audio/Z.m4a' },
    { char: 'Ž', audio: 'audio/Z1.m4a' },
    // Add more letters as needed
  ];